//@GeneratedCode
namespace QTBookShop.Logic.Contracts.Base
{
    using TOutModel = Models.Base.Author;
    ///
    /// Generated by the generator
    ///
    public partial interface IAuthorsAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
