//@GeneratedCode
namespace QTBookShop.Logic.Contracts.Base
{
    using TOutModel = Models.Base.Category;
    ///
    /// Generated by the generator
    ///
    public partial interface ICategoriesAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
