//@GeneratedCode
namespace QTBookShop.Logic.Contracts.App
{
    using TOutModel = Models.App.Book;
    ///
    /// Generated by the generator
    ///
    public partial interface IBooksAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
