//@GeneratedCode
namespace QTBookShop.Logic.Contracts.App
{
    using TOutModel = Models.App.Order;
    ///
    /// Generated by the generator
    ///
    public partial interface IOrdersAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
