//@GeneratedCode
namespace QTBookShop.Logic.Facades.App
{
    using TOutModel = Models.App.Book;
    ///
    /// Generated by the generator
    ///
    public sealed partial class BooksFacade : ControllerFacade<TOutModel>, Contracts.App.IBooksAccess
    {
        ///
        /// Generated by the generator
        ///
        static BooksFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public BooksFacade()
        : base(new QTBookShop.Logic.Controllers.App.BooksController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public BooksFacade(FacadeObject facadeObject)
        : base(new QTBookShop.Logic.Controllers.App.BooksController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
