//@GeneratedCode
namespace QTBookShop.Logic.Facades.App
{
    using TOutModel = Models.App.Order;
    ///
    /// Generated by the generator
    ///
    public sealed partial class OrdersFacade : ControllerFacade<TOutModel>, Contracts.App.IOrdersAccess
    {
        ///
        /// Generated by the generator
        ///
        static OrdersFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public OrdersFacade()
        : base(new QTBookShop.Logic.Controllers.App.OrdersController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public OrdersFacade(FacadeObject facadeObject)
        : base(new QTBookShop.Logic.Controllers.App.OrdersController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
