//@GeneratedCode
namespace QTBookShop.Logic.Facades.Base
{
    using TOutModel = Models.Base.Category;
    ///
    /// Generated by the generator
    ///
    public sealed partial class CategoriesFacade : ControllerFacade<TOutModel>, Contracts.Base.ICategoriesAccess
    {
        ///
        /// Generated by the generator
        ///
        static CategoriesFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public CategoriesFacade()
        : base(new QTBookShop.Logic.Controllers.Base.CategoriesController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public CategoriesFacade(FacadeObject facadeObject)
        : base(new QTBookShop.Logic.Controllers.Base.CategoriesController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
