//@GeneratedCode
namespace QTBookShop.Logic.DataContext
{
    ///
    /// Generated by the generator
    ///
    partial class ProjectDbContext
    {
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.Base.Author>? AuthorSet{ get; set; }
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.Base.Category>? CategorySet{ get; set; }
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.App.Book>? BookSet{ get; set; }
        ///
        /// Generated by the generator
        ///
        public DbSet<Entities.App.Order>? OrderSet{ get; set; }
        
        ///
        /// Generated by the generator
        ///
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.EntityObject
        {
            if (typeof(E) == typeof(Entities.Base.Author))
            {
                dbSet = AuthorSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Base.Category))
            {
                dbSet = CategorySet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.Book))
            {
                dbSet = BookSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.Order))
            {
                dbSet = OrderSet as DbSet<E>;
                handled = true;
            }
        }
    }
}
